import type { NextPage } from 'next'
import Head from 'next/head'
import React, { useState } from 'react'
import { SiPrisma, SiTailwindcss, SiNextdotjs } from 'react-icons/si'
import isUrlValid from '../utils/url-validator'

// TODO: Get total uses of links
// TODO: Animate it with tweening (it increases from 0 to total)
// TODO: Courusel
// TODO: Page with total redirects to a specific page
// TODO: Captcha? Just for UI though
// TODO: Try making randomly generated animation (e.g. blurry bubbles on the header background)
// TODO: Test every page with each break-point
interface Section {
    icon : JSX.Element,
    header : string,
    text : JSX.Element
}

const sectionClasses = {
    next : `text-8xl transition-colors hocus-active:text-[#0070f3] focus:outline-none`,
    prisma : `text-8xl transition-colors hocus-active:text-[#7baeea] focus:outline-none`,
    tailwind : `text-8xl transition-colors hocus-active:text-[#0ea5e9] focus:outline-none`
} 

const sections : Section[] = [
    {
        header : 'Lorem ipsum',
        text : (
            <>
            Lorem ipsum dolor sit amet, <i>consectetur adipisicing elit.</i>
            Odit maiores blanditiis labore, voluptatem facilis nesciunt.
            </>
        ),
        icon : (
            <a target="_blank" href="https://nextjs.org/" className={sectionClasses.next}>
                <SiNextdotjs />
            </a>
        )
    },
    {
        header : 'Consectetur adipisicing',
        text : (
            <>
            Consectetur adipisicing elit. Soluta, voluptas!
            Sit amet consectetur <i>adipisicing elit</i>. Temporibus, molestiae?
            </>
        ),
        icon : (
            <a target="_blank" href="https://www.prisma.io/" className={sectionClasses.prisma}>
                <SiPrisma />
            </a>
        )
    },
    {
        header : 'Placeat in ad odit',
        text : (
            <>
            Placeat in ad <i>odit ex suscipit eum</i> magnam saepe blanditiis dicta,
            officia explicabo ratione adipisci minus cum accusamus <i>porro</i> rerum iusto quia!
            </>
        ),
        icon : (
            <a target="_blank" href="https://tailwindcss.com/" className={sectionClasses.tailwind}>
                <SiTailwindcss />
            </a>
        )
    }
]

const Home: NextPage = () => {
    const [error, setError] = useState('')
    const [url, setUrl] = useState('');
    
    const handleSubmit = (e : React.FormEvent<HTMLFormElement>) => {
        if (!isUrlValid(url)) {
            e.preventDefault()
            setError('Error: Invalid Url')
        }
    }
    
    return (
        <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="flex flex-col items-center body-wrapper child:max-w-xl">
            <header className="flex flex-col items-center gap-4 py-10">
                <h1 className="text-center font-bold tracking-wide">Link Shortener</h1>
                <h3 className="text-center tracking-wide">Make your URLs shorter</h3>
            </header>
            <span className="self-start empty:h-0 h-[2em] px-5 overflow-y-hidden transition-[height] text-red rounded-sm">{error}</span>
            <form onSubmit={handleSubmit} method="POST" action="/add/" className="flex tablet:text-xl flex-col items-center gap-4 bg-red tablet:rounded-md w-full py-10 px-5 tablet:py-11 tablet:px-5">
                <div className="text-lg w-full relative">
                    {/* Placeholder opacity doesn't work for some reason  */}
                    <input
                        id="url-input"
                        name="url"
                        value={url}
                        onChange={e => setUrl(e.currentTarget.value)}
                        className="w-full peer placeholder-0 tablet:text-2xl"
                        type="text"
                        placeholder="URL"
                    />
                    <label
                        className={`absolute
                        tablet:text-2xl
                        
                        peer-placeholder-shown:top-1/2
                        peer-placeholder-shown:-translate-y-1/2
                        peer-placeholder-shown:left-1
                        peer-placeholder-shown:text-black
                        peer-placeholder-shown:opacity-60

                        peer-focus:-top-1/1
                        peer-focus:translate-y-1
                        peer-focus:left-1
                        peer-focus:text-white
                        peer-focus:opacity-100
                        
                        opacity-100
                        -top-1/1
                        translate-y-1
                        text-white
                        left-1
                        transition-all
                        `}
                        htmlFor="url-input"
                    >
                        URL
                    </label>
                </div>
                <button className="w-full transition-colors">Shorten</button>
            </form>
            <div className={`
                flex flex-col items-center
                tablet:flex-row tablet:max-w-7xl tablet:mt-20 tablet:child:flex-1 tablet:items-stretch
                gap-10 py-10 px-4 text-lg text-center`}>
                {
                    sections.map((sec, idx) => (
                        <section key={`section-${idx}`} className={`flex flex-col opacity-0 items-center tablet:justify-between gap-3 animate-[sectionfadein_.5s_ease-in-out_1]`} style={{
                            animationDelay : `${300 + 300 * idx}ms`,
                            animationFillMode : 'forwards'
                        }}>
                            <h3 className="font-bold text-xl">{sec.header}</h3>
                            <p className="italic-child:underline italic-child:decoration-red italic-child:decoration-2">{sec.text}</p>
                            {sec.icon}
                        </section>
                    ))
                }
            </div>
        </div>
        </>
    )
}

export default Home
