import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'

interface Props {
    fromServer : {
        message : string
    }
}

const Home: NextPage<Props> = ({fromServer}) => {
    const [data, setData] = useState({
        message : ''
    })
    
    useEffect(() => {
        if (data.message) return
        fetch('/api/hello').then(response => response.json()).then(setData)
    }, [])
    
    return (
        <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="text-4xl font-light bg-slate-800 text-white w-full h-[100vh] flex flex-col gap-4 items-center justify-center">
            <span>{data.message || 'Loading...'}</span>
            <span>{fromServer.message}</span>
            <span>
                This is made with{' '}
                <a target="_blank" href="https://nextjs.org" className="hover:text-blue-400 transition-colors">Next.js</a>
                {' '}&{' '}
                <a target="_blank" href="https://tailwind.com" className="hover:text-blue-400 transition-colors">TailwindCSS</a>
            </span>
        </div>
        </>
    )
}

const getSomeServerData = () => {
    return {
        message : "This message was rendered on the server"
    }
}

export async function getServerSideProps() {
    return {
        props : {
            fromServer : getSomeServerData()
        }
    }
}

export default Home
